[package]
name = "simple-map"
version = "2.0.0-rc4"
authors = ['Substrate DevHub <https://github.com/substrate-developer-hub>']
repository = 'https://github.com/substrate-developer-hub/recipes'
edition = "2018"
license = "GPL-3.0-or-later"
description = "A pallet that demonstrates Substrate's storage maps"

[package.metadata.substrate]
categories = [
	"pallet",
	"tutorial",
	"recipe",
]
compatibility_version = "2.0.0-rc4"

[features]
default = ['std']
std = [
    'parity-scale-codec/std',
    'frame-support/std',
    'frame-system/std',
]

[dependencies]
parity-scale-codec = { default-features = false, features = ['derive'], version = '1.3.0' }
frame-support = { version = '2.0.0-rc4', default-features = false }
frame-system = { version = '2.0.0-rc4', default-features = false }

[dev-dependencies]
sp-runtime = { version = '2.0.0-rc4', default-features = false }
sp-core = { version = '2.0.0-rc4', default-features = false }
sp-io = { version = '2.0.0-rc4', default-features = false }
