[package]
name = "simple-map"
version = "3.0.0"
edition = "2018"
authors = ['Substrate DevHub <https://github.com/substrate-developer-hub>']
repository = 'https://github.com/substrate-developer-hub/recipes'
description = "A pallet that demonstrates Substrate's storage maps"
license = "GPL-3.0-or-later"

[dependencies]
parity-scale-codec = { default-features = false, features = ['derive'], version = '2.0' }

# Substrate packages
frame-support = { version = '3.0', default-features = false }
frame-system = { version = '3.0', default-features = false }

[dev-dependencies]
serde = '1.0'
sp-core = '3.0'
sp-io = '3.0'
sp-runtime = '3.0'

[features]
default = ['std']
std = [
	'frame-support/std',
	'frame-system/std',
	'parity-scale-codec/std',
]
