[package]
authors = ['Substrate DevHub <https://github.com/substrate-developer-hub>']
edition = '2018'
name = 'sha3pow'
repository = 'https://github.com/substrate-developer-hub/recipes'
version = "2.0.0-rc4"
description = 'Sha3-based Proof of Work algorithms for Substrate'
license = "GPL-3.0-or-later"

[package.metadata.substrate]
categories = [
	"consensus",
	"recipe",
]
compatibility_version = "2.0.0-rc4"

[dependencies]
parity-scale-codec = '1.3.0'
sha3 = "0.8"
rand = { version = "0.7", features = ["small_rng"] }
sc-consensus-pow = '0.8.0-rc4'
sp-api = '2.0.0-rc4'
sp-consensus-pow = '0.8.0-rc4'
sp-core = '2.0.0-rc4'
sp-runtime = '2.0.0-rc4'
