[package]
name = "hybrid-consensus"
version = "2.0.0-rc6"
edition = "2018"
authors = ['Substrate DevHub <https://github.com/substrate-developer-hub>']
repository = 'https://github.com/substrate-developer-hub/recipes'
description = 'A Substrate node with PoW authoring and PoA finality'
license = "GPL-3.0-or-later"

[package.metadata.substrate]
categories = [
	"Node",
	"PoW",
	"GRANDPA",
	"Hybrid-consensus",
	"tutorial",
	"recipe",
]
compatibility_version = "2.0.0-rc6"

[[bin]]
name = "hybrid-consensus"
path = "src/main.rs"

[dependencies]
derive_more = "0.15.0"
futures = "0.3.1"
structopt = "0.3.8"
futures01 = { package = "futures", version = "0.1.29" }
ctrlc = { version = "3.1.3", features = ["termination"] }
log = "0.4.8"
tokio = "0.1.22"
exit-future = "0.2.0"
parking_lot = "0.9.0"
trie-root = "0.15.2"
sp-io = '2.0.0-rc6'
sc-cli = '0.8.0-rc4'
sc-client-api = '2.0.0-rc6'
sp-core = '2.0.0-rc6'
sp-runtime = '2.0.0-rc6'
sc-executor = '0.8.0-rc4'
sc-service = '0.8.0-rc4'
sp-inherents = '2.0.0-rc6'
sp-timestamp = '2.0.0-rc6'
sc-transaction-pool = '2.0.0-rc6'
sp-transaction-pool = '2.0.0-rc6'
sc-network = '0.8.0-rc4'
sc-finality-grandpa = '0.8.0-rc4'
sp-finality-grandpa = '2.0.0-rc6'
sc-basic-authorship = '0.8.0-rc4'
sp-consensus = '0.8.0-rc4'
sc-consensus = '0.8.0-rc4'
sc-consensus-pow = '0.8.0-rc4'
sp-consensus-pow = '0.8.0-rc4'
sha3pow = { path = '../../consensus/sha3pow' }
sp-api = '2.0.0-rc6'

runtime = { package = "minimal-grandpa-runtime", path = "../../runtimes/minimal-grandpa-runtime"}


[build-dependencies]
vergen = "3.0.4"
substrate-build-script-utils = '2.0.0-rc6'
