[package]
name = "kitchen-node"
version = "2.0.0"
authors = ["Anonymous"]
build = "build.rs"
edition = "2018"

[[bin]]
name = "kitchen-node"
path = "src/main.rs"

[dependencies]
derive_more = "0.15.0"
futures = "0.1.29"
ctrlc = { version = "3.1.3", features = ["termination"] }
log = "0.4.8"
tokio = "0.1.22"
exit-future = "0.1.4"
parking_lot = "0.9.0"
codec = { package = "parity-scale-codec", version = "1.0.0" }
trie-root = "0.15.2"
sr-io = { git = 'https://github.com/paritytech/substrate.git', branch = 'master' }
substrate-cli = { git = 'https://github.com/paritytech/substrate.git', branch = 'master' }
primitives = { package = "substrate-primitives", git = 'https://github.com/paritytech/substrate.git', branch = 'master' }
substrate-executor = { git = 'https://github.com/paritytech/substrate.git', branch = 'master' }
substrate-service = { git = 'https://github.com/paritytech/substrate.git', branch = 'master' }
inherents = { package = "substrate-inherents", git = 'https://github.com/paritytech/substrate.git', branch = 'master' }
transaction-pool = { package = "substrate-transaction-pool", git = 'https://github.com/paritytech/substrate.git', branch = 'master' }
network = { package = "substrate-network", git = 'https://github.com/paritytech/substrate.git', branch = 'master' }
babe = { package = "substrate-consensus-babe", git = 'https://github.com/paritytech/substrate.git', branch = 'master' }
babe-primitives = { package = "substrate-consensus-babe-primitives", git = 'https://github.com/paritytech/substrate.git', branch = 'master' }
grandpa = { package = "substrate-finality-grandpa", git = 'https://github.com/paritytech/substrate.git', branch = 'master' }
grandpa-primitives = { package = "substrate-finality-grandpa-primitives", git = 'https://github.com/paritytech/substrate.git', branch = 'master' }
substrate-client = { git = 'https://github.com/paritytech/substrate.git', branch = 'master' }
basic-authorship = { package = "substrate-basic-authorship", git = 'https://github.com/paritytech/substrate.git', branch = 'master' }

# Edit these lines to point to a different runtime.
# Your runtime must have the necessary runtime modules to support consensus (Babe, Grandpa, etc)
runtime = { package = "super-runtime", path = "../runtimes/super-runtime" }
runtime-genesis = { package = "super-genesis", path = "../runtimes/super-genesis" }
# runtime = { package = "weight-fee-runtime", path = "../runtimes/weight-fee-runtime"}
# runtime-genesis = { package = "weight-fee-genesis", path = "../runtimes/weight-fee-genesis"}

[build-dependencies]
vergen = "3.0.4"
