[package]
name = 'super-genesis'
version = "2.0.0"
authors = ["Anonymous"]
edition = "2018"

[dependencies.runtime]
package = 'super-runtime'
path = '../super-runtime'

[dependencies]
babe-primitives = { package = "substrate-consensus-babe-primitives", git = "https://github.com/paritytech/substrate", rev = '6ae3b6c4ddc03d4cdb10bd1d417b95d20f4c1b6e' }
grandpa-primitives = { package = "substrate-finality-grandpa-primitives", git = "https://github.com/paritytech/substrate", rev = '6ae3b6c4ddc03d4cdb10bd1d417b95d20f4c1b6e' }
