[package]
name = "weight-fee-runtime"
version = "2.0.0-rc4"
authors = ['Substrate DevHub <https://github.com/substrate-developer-hub>']
repository = 'https://github.com/substrate-developer-hub/recipes'
edition = "2018"
license = "GPL-3.0-or-later"
description = "A runtime that demonstrate converting weights to fees and charging fees in multiple assets"

[package.metadata.substrate]
categories = [
	"runtime",
	"Weights",
	"fees",
	"Assets",
	"tutorial",
	"recipe",
]
compatibility_version = "2.0.0-rc4"

[dependencies]
serde = { version = "1.0", optional = true, features = ["derive"] }
weights = { path = "../../pallets/weights", default-features = false }
parity-scale-codec = { version = "1.3.0", features = ["derive"], default-features = false }
smallvec = "1.4"

frame-executive = { version = '2.0.0-rc4', default-features = false }
frame-support = { version = '2.0.0-rc4', default-features = false }
frame-system = { version = '2.0.0-rc4', default-features = false }
sp-api = { version = '2.0.0-rc4', default-features = false }
sp-block-builder = { version = '2.0.0-rc4', default-features = false }
sp-core = { version = '2.0.0-rc4', default-features = false }
sp-inherents = { version = '2.0.0-rc4', default-features = false }
sp-io = { version = '2.0.0-rc4', default-features = false }
sp-offchain = { version = '2.0.0-rc4', default-features = false }
sp-runtime = { version = '2.0.0-rc4', default-features = false }
sp-session = { version = '2.0.0-rc4', default-features = false }
sp-std = { version = '2.0.0-rc4', default-features = false }
sp-transaction-pool = { version = '2.0.0-rc4', default-features = false }
sp-version = { version = '2.0.0-rc4', default-features = false }

balances = { package = 'pallet-balances', version = '2.0.0-rc4', default-features = false }
generic-asset = { package = 'pallet-generic-asset', version = '2.0.0-rc4', default-features = false }
transaction-payment = { package = 'pallet-transaction-payment', version = '2.0.0-rc4', default-features = false }
randomness-collective-flip = { package = 'pallet-randomness-collective-flip', version = '2.0.0-rc4', default-features = false }
timestamp = { package = 'pallet-timestamp', version = '2.0.0-rc4', default-features = false }
sudo = { package = 'pallet-sudo', version = '2.0.0-rc4', default-features = false }

[build-dependencies]
wasm-builder-runner = { package = "substrate-wasm-builder-runner", version = "1.0.4" }

[features]
default = ["std"]
std = [
	"balances/std",
	"sp-block-builder/std",
	"frame-executive/std",
	"generic-asset/std",
	"sp-inherents/std",
	"sp-offchain/std",
	"parity-scale-codec/std",
	"randomness-collective-flip/std",
	"sp-std/std",
	"sp-io/std",
	"serde",
	"sp-api/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-session/std",
	"sudo/std",
	"frame-support/std",
	"frame-system/std",
	"timestamp/std",
	"transaction-payment/std",
	"sp-version/std",
	"weights/std",
	"sp-transaction-pool/std",
]
