[package]
name = "sum-storage"
version = "2.0.0-rc5"
authors = ['Substrate DevHub <https://github.com/substrate-developer-hub>']
edition = "2018"
description = "A pallet with two storage items whose sum is exposed via a custom runtime API"
license = "GPL-3.0-or-later"
repository = "https://github.com/substrate-developer-hub/recipes"

[package.metadata.substrate]
categories = [
	"Runtime API",
	"tutorial",
	"recipe",
]
compatibility_version = "2.0.0-rc5"


[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.0", default-features = false, features = ["derive"] }
sp-std = { version = '2.0.0-rc5', default-features = false}
sp-runtime = { version = '2.0.0-rc5', default-features = false}
frame-support = { version = '2.0.0-rc5', default-features = false}
frame-system = { version = '2.0.0-rc5', default-features = false}


[dev-dependencies]
sp-io = { version = '2.0.0-rc5', default-features = false}
sp-core = { version = '2.0.0-rc5', default-features = false}

[features]
default = ["std"]
std = [
	"codec/std",
	"sp-std/std",
	"sp-runtime/std",
	"frame-support/std",
	"frame-system/std",
]
