version: 2
jobs:
  test:
    docker:
      - image: parity/rust:nightly
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      # - restore_cache:
      #     keys:
      #       - v1-dependencies-{{ checksum "package.json" }}
      #       # fallback to using the latest cache if no exact match is found
      #       - v1-dependencies-
      # - run:
      #     name: Install
      #     command: |
      #       sudo apt-get install libusb-1.0-0-dev
      #       yarn install
      # - save_cache:
      #     paths:
      #       - node_modules
      #     key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: 
          command: yarn lint:ci
      - run:
          name: Test
          command: yarn test
      - persist_to_workspace:
          # relative to working_directory
          root: "./"
          paths:
            - "./"

  deploy:
    docker:
      - image: circleci/node:10.16
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Build & Deploy
          # added skip host key checking to avoid the manual prompt
          command: |
            mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
            git config --global user.email "devhub-deploy@users.noreply.github.com"
            git config --global user.name "Devhub Deployer"
            yarn deploy
workflows:
  version: 2
  test_deploy:
    jobs:
      - test:
          filters: *filter-non-gh-pages
      - deploy:
          filters: *filter-only-master
          requires:
            - test
