[package]
name = "api-runtime"
version = "2.0.0"
edition = "2018"
authors = ['Substrate DevHub <https://github.com/substrate-developer-hub>']
repository = 'https://github.com/substrate-developer-hub/recipes'
description = "A runtime that features a custom runtime API that calls into a pallet"
license = "GPL-3.0-or-later"

[package.metadata.substrate]
categories = [
	"runtime",
	"runtime API",
	"tutorial",
	"recipe",
]
compatibility_version = "2.0.0"

[dependencies]
parity-scale-codec = { version = "1.3.0", default-features = false, features = ["derive"] }
serde = { version = "1.0.101", optional = true, features = ["derive"] }

# Substrate packages

frame-executive = { version = '2.0.0', default-features = false}
frame-support = { version = '2.0.0', default-features = false }
frame-system = { version = '2.0.0', default-features = false }
pallet-balances = { version = '2.0.0', default-features = false }
pallet-randomness-collective-flip = { version = '2.0.0', default-features = false }
pallet-sudo = { version = '2.0.0', default-features = false }
pallet-timestamp = { version = '2.0.0', default-features = false }
pallet-transaction-payment = { version = '2.0.0', default-features = false }
sp-api = { version = '2.0.0', default-features = false }
sp-block-builder = { version = '2.0.0', default-features = false }
sp-core = { version = '2.0.0', default-features = false }
sp-inherents = { version = '2.0.0', default-features = false }
sp-io = { version = '2.0.0', default-features = false }
sp-offchain = { version = '2.0.0', default-features = false }
sp-runtime = { version = '2.0.0', default-features = false }
sp-session = { version = '2.0.0', default-features = false }
sp-std = { version = '2.0.0', default-features = false }
sp-transaction-pool = { version = '2.0.0', default-features = false }
sp-version = { version = '2.0.0', default-features = false }

# local packages

sum-storage = { default-features = false, path = "../../pallets/sum-storage" }
sum-storage-runtime-api = { default-features = false, path = "../../pallets/sum-storage/runtime-api" }

[build-dependencies]
substrate-wasm-builder-runner = { version = "1.0.4" }

[features]
default = ["std"]
std = [
	"frame-executive/std",
	"frame-support/std",
	"frame-system/std",
	"pallet-balances/std",
	"pallet-randomness-collective-flip/std",
	"pallet-sudo/std",
	"pallet-timestamp/std",
	"pallet-transaction-payment/std",
	"parity-scale-codec/std",
	"serde",
	"sp-api/std",
	"sp-block-builder/std",
	"sp-core/std",
	"sp-inherents/std",
	"sp-io/std",
	"sp-offchain/std",
	"sp-runtime/std",
	"sp-session/std",
	"sp-std/std",
	"sp-transaction-pool/std",
	"sp-version/std",
	"sum-storage-runtime-api/std",
	"sum-storage/std",
]
