[package]
name = "ocw-runtime"
version = "2.0.0-rc5"
authors = ['Substrate DevHub <https://github.com/substrate-developer-hub>']
repository = 'https://github.com/substrate-developer-hub/recipes'
edition = "2018"
license = "GPL-3.0-or-later"
description = "A runtime that demonstrates using offchain workers"

[package.metadata.substrate]
categories = [
	"runtime",
	"offchain worker",
	"tutorial",
	"recipe",
]
compatibility_version = "2.0.0-rc5"

[dependencies]
serde = { version = "1.0", optional = true, features = ["derive"] }
parity-scale-codec = { version = "1.3.0", features = ["derive"], default-features = false }

# Substrate pallets & dependencies
frame-executive = { version = '2.0.0-rc5', default-features = false }
frame-support = { version = '2.0.0-rc5', default-features = false }
frame-system = { version = '2.0.0-rc5', default-features = false }
pallet-balances = { version = '2.0.0-rc5', default-features = false }
pallet-indices = { version = '2.0.0-rc5', default-features = false }
pallet-randomness-collective-flip = { version = '2.0.0-rc5', default-features = false }
pallet-sudo = { version = '2.0.0-rc5', default-features = false }
pallet-timestamp = { version = '2.0.0-rc5', default-features = false }
pallet-transaction-payment = { version = '2.0.0-rc5', default-features = false }
sp-api = { version = '2.0.0-rc5', default-features = false }
sp-block-builder = { version = '2.0.0-rc5', default-features = false }
sp-core = { version = '2.0.0-rc5', default-features = false }
sp-inherents = { version = '2.0.0-rc5', default-features = false }
sp-io = { version = '2.0.0-rc5', default-features = false }
sp-offchain = { version = '2.0.0-rc5', default-features = false }
sp-runtime = { version = '2.0.0-rc5', default-features = false }
sp-session = { version = '2.0.0-rc5', default-features = false }
sp-std = { version = '2.0.0-rc5', default-features = false }
sp-transaction-pool = { version = '2.0.0-rc5', default-features = false }
sp-version = { version = '2.0.0-rc5', default-features = false }

# Recipe Pallets
offchain-demo = { path = "../../pallets/offchain-demo", default-features = false }

[build-dependencies]
wasm-builder-runner = { package = "substrate-wasm-builder-runner", version = "1.0.4" }

[features]
default = ["std"]
std = [
	# Substrate dependencies alphabetically
	"frame-executive/std",
	"frame-support/std",
	"frame-system/std",
	"pallet-balances/std",
	"pallet-indices/std",
	"pallet-randomness-collective-flip/std",
	"pallet-sudo/std",
	"pallet-timestamp/std",
	"pallet-transaction-payment/std",
	"parity-scale-codec/std",
	"serde",
	"sp-api/std",
	"sp-block-builder/std",
	"sp-core/std",
	"sp-inherents/std",
	"sp-io/std",
	"sp-offchain/std",
	"sp-runtime/std",
	"sp-session/std",
	"sp-std/std",
	"sp-transaction-pool/std",
	"sp-version/std",

	# Recipes pallets
	"offchain-demo/std",
]
