[package]
name = "sum-storage-rpc"
version = "2.0.0"
authors = ['Substrate DevHub <https://github.com/substrate-developer-hub>']
edition = "2018"
license = "GPL-3.0-or-later"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.0" }
jsonrpc-core = "14.0.3"
jsonrpc-core-client = "14.0.3"
jsonrpc-derive = "14.0.3"
serde = { version = "1.0.101", features = ["derive"], optional = true }

sp-rpc = { version = '2.0.0-rc6', default-features = false}
sp-runtime = { version = '2.0.0-rc6', default-features = false}
sp-blockchain = { version = '2.0.0-rc6', default-features = false}
sp-api = { version = '2.0.0-rc6', default-features = false }

sum-storage-runtime-api = { version = "2.0.0", path = "../runtime-api", default-features = false }

[features]
default = ["std"]
std = [
  "serde",
  "sp-runtime/std",
  "sp-api/std",
  "sum-storage-runtime-api/std"
]
