[package]
name = "sum-storage-rpc"
version = "2.0.0"
authors = ["JoshyOrndorff"]
edition = "2018"
license = "GPL-3.0-or-later"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.0" }
jsonrpc-core = "14.0.3"
jsonrpc-core-client = "14.0.3"
jsonrpc-derive = "14.0.3"
serde = { version = "1.0.101", features = ["derive"], optional = true }

sp-rpc = { version = '2.0.0-alpha.6', default_features = false}
sp-runtime = { version = '2.0.0-alpha.6', default_features = false}
sp-blockchain = { version = '2.0.0-alpha.6', default_features = false}
sp-api = { version = '2.0.0-alpha.6', default_features = false }

sum-storage-runtime-api = { version = "2.0.0", path = "../runtime-api", default_features = false }

[features]
default = ["std"]
std = [
  "serde",
  "sp-runtime/std",
  "sp-api/std",
  "sum-storage-runtime-api/std"
]
