[package]
name = "super-runtime"
version = "2.0.0"
authors = ["Anonymous"]
edition = "2018"

[dependencies]
serde = { version = "1.0", optional = true, features = ["derive"] }
safe-mix = { version = "1.0", default-features = false }
# Substrate Pallets
balances = { package = 'pallet-balances', git = 'https://github.com/paritytech/substrate.git', rev = '1d8fa432949b99fac4ea0bebfdd6675dee973aa1', default-features = false }
transaction-payment = { package = 'pallet-transaction-payment', git = 'https://github.com/paritytech/substrate.git', rev = '1d8fa432949b99fac4ea0bebfdd6675dee973aa1', default-features = false }
# Recipe Pallets
adding-machine = { path = "../../pallets/adding-machine", default-features = false }
basic-token = { path = "../../pallets/basic-token", default-features = false }
charity = { path = "../../pallets/charity", default-features = false }
check-membership = { path = "../../pallets/check-membership", default-features = false }
compounding-interest = { path = "../../pallets/compounding-interest", default-features = false }
constant-config = { path = "../../pallets/constant-config", default-features = false }
default-instance = { path = "../../pallets/default-instance", default-features = false }
double-map = { path = "../../pallets/double-map", default-features = false }
execution-schedule = { path = "../../pallets/execution-schedule", default-features = false }
fixed-point = { path = "../../pallets/fixed-point", default-features = false }
generic-event = { path = "../../pallets/generic-event", default-features = false }
hello-substrate = { path = "../../pallets/hello-substrate", default-features = false }
last-caller = { path = "../../pallets/last-caller", default-features = false }
ringbuffer-queue = { path = "../../pallets/ringbuffer-queue", default_features = false }
randomness = { path = "../../pallets/randomness", default_features = false }
simple-event = { path = "../../pallets/simple-event", default_features = false }
simple-map = { path = "../../pallets/simple-map", default-features = false }
single-value = { path = "../../pallets/single-value", default-features = false }
storage-cache = { path = "../../pallets/storage-cache", default-features = false }
struct-storage = { path = "../../pallets/struct-storage", default-features = false }
vec-set = { path = "../../pallets/vec-set", default-features = false }

[dependencies.parity-scale-codec]
default-features = false
features = ['derive']
version = '1.0.6'

[dependencies.rstd]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = "sp-std"
rev = '1d8fa432949b99fac4ea0bebfdd6675dee973aa1'

[dependencies.runtime-io]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-io'
rev = '1d8fa432949b99fac4ea0bebfdd6675dee973aa1'

[dependencies.sp-offchain]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
rev = '1d8fa432949b99fac4ea0bebfdd6675dee973aa1'

[dependencies.version]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-version'
rev = '1d8fa432949b99fac4ea0bebfdd6675dee973aa1'

[dependencies.support]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'frame-support'
rev = '1d8fa432949b99fac4ea0bebfdd6675dee973aa1'

[dependencies.sp-core]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
rev = '1d8fa432949b99fac4ea0bebfdd6675dee973aa1'

[dependencies.substrate-session]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-session'
rev = '1d8fa432949b99fac4ea0bebfdd6675dee973aa1'

[dependencies.babe]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-babe'
rev = '1d8fa432949b99fac4ea0bebfdd6675dee973aa1'

[dependencies.sp-consensus-babe]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
rev = '1d8fa432949b99fac4ea0bebfdd6675dee973aa1'

[dependencies.sp-finality-grandpa]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
rev = '1d8fa432949b99fac4ea0bebfdd6675dee973aa1'

[dependencies.executive]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'frame-executive'
rev = '1d8fa432949b99fac4ea0bebfdd6675dee973aa1'

[dependencies.indices]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-indices'
rev = '1d8fa432949b99fac4ea0bebfdd6675dee973aa1'

[dependencies.grandpa]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-grandpa'
rev = '1d8fa432949b99fac4ea0bebfdd6675dee973aa1'

[dependencies.randomness-collective-flip]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-randomness-collective-flip'
rev = '1d8fa432949b99fac4ea0bebfdd6675dee973aa1'

[dependencies.system]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'frame-system'
rev = '1d8fa432949b99fac4ea0bebfdd6675dee973aa1'

[dependencies.timestamp]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-timestamp'
rev = '1d8fa432949b99fac4ea0bebfdd6675dee973aa1'

[dependencies.sudo]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-sudo'
rev = '1d8fa432949b99fac4ea0bebfdd6675dee973aa1'

[dependencies.sp-runtime]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-runtime'
rev = '1d8fa432949b99fac4ea0bebfdd6675dee973aa1'

[dependencies.sp-api]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
rev = '1d8fa432949b99fac4ea0bebfdd6675dee973aa1'

[dependencies.block-builder-api]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-block-builder'
rev = '1d8fa432949b99fac4ea0bebfdd6675dee973aa1'

[dependencies.sp-transaction-pool]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
rev = '1d8fa432949b99fac4ea0bebfdd6675dee973aa1'

[dependencies.inherents]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-inherents'
rev = '1d8fa432949b99fac4ea0bebfdd6675dee973aa1'

[build-dependencies]
wasm-builder-runner = { package = "substrate-wasm-builder-runner", version = "1.0.4" }

[features]
default = ["std"]
std = [
	# Substrate dependencies alphabetically
	"babe/std",
	"balances/std",
	"block-builder-api/std",
	"executive/std",
	"grandpa/std",
	"indices/std",
	"inherents/std",
	"parity-scale-codec/std",
	"sp-consensus-babe/std",
	"sp-core/std",
	"sp-offchain/std",
	"sp-finality-grandpa/std",
	"randomness-collective-flip/std",
	"rstd/std",
	"runtime-io/std",
	"safe-mix/std",
	"serde",
	"sp-api/std",
	"sp-runtime/std",
	"sp-transaction-pool/std",
	"substrate-session/std",
	"sudo/std",
	"support/std",
	"system/std",
	"timestamp/std",
	"transaction-payment/std",
	"version/std",

	# Recipes pallets
	"adding-machine/std",
	"basic-token/std",
	"charity/std",
	"check-membership/std",
	"compounding-interest/std",
	"constant-config/std",
	"default-instance/std",
	"double-map/std",
	"execution-schedule/std",
	"fixed-point/std",
	"generic-event/std",
	"hello-substrate/std",
	"last-caller/std",
	"randomness/std",
	"ringbuffer-queue/std",
	"simple-event/std",
	"simple-map/std",
	"single-value/std",
	"storage-cache/std",
	"struct-storage/std",
	"vec-set/std",
]
