[package]
name = "super-runtime"
version = "2.0.0-rc6"
authors = ['Substrate DevHub <https://github.com/substrate-developer-hub>']
repository = 'https://github.com/substrate-developer-hub/recipes'
edition = "2018"
license = "GPL-3.0-or-later"
description = "A runtime that houses most of the Recipes' pallets"

[package.metadata.substrate]
categories = [
	"runtime",
	"tutorial",
	"recipe",
]
compatibility_version = "2.0.0-rc6"

[dependencies]
parity-scale-codec = { version = "1.3.0", default-features = false, features = ["derive"] }
serde = { version = "1.0", optional = true, features = ["derive"] }

# Substrate Pallets
balances = { package = 'pallet-balances', version = '2.0.0-rc6', default-features = false }
randomness-collective-flip = { package = 'pallet-randomness-collective-flip', version = '2.0.0-rc6', default-features = false }
sudo = { package = 'pallet-sudo', version = '2.0.0-rc6', default-features = false }
transaction-payment = { package = 'pallet-transaction-payment', version = '2.0.0-rc6', default-features = false }
timestamp = { package = 'pallet-timestamp', version = '2.0.0-rc6', default-features = false }

# Recipe Pallets
basic-token = { path = "../../pallets/basic-token", default-features = false }
charity = { path = "../../pallets/charity", default-features = false }
check-membership = { path = "../../pallets/check-membership", default-features = false }
compounding-interest = { path = "../../pallets/compounding-interest", default-features = false }
constant-config = { path = "../../pallets/constant-config", default-features = false }
default-instance = { path = "../../pallets/default-instance", default-features = false }
double-map = { path = "../../pallets/double-map", default-features = false }
fixed-point = { path = "../../pallets/fixed-point", default-features = false }
generic-event = { path = "../../pallets/generic-event", default-features = false }
hello-substrate = { path = "../../pallets/hello-substrate", default-features = false }
last-caller = { path = "../../pallets/last-caller", default-features = false }
map-set = { path = "../../pallets/map-set", default-features = false }
ringbuffer-queue = { path = "../../pallets/ringbuffer-queue", default-features = false }
randomness = { path = "../../pallets/randomness", default-features = false }
simple-crowdfund = { path = "../../pallets/simple-crowdfund", default-features = false}
simple-event = { path = "../../pallets/simple-event", default-features = false }
simple-map = { path = "../../pallets/simple-map", default-features = false }
storage-cache = { path = "../../pallets/storage-cache", default-features = false }
struct-storage = { path = "../../pallets/struct-storage", default-features = false }
vec-set = { path = "../../pallets/vec-set", default-features = false }

# Other Substrate dependencies
frame-executive = { version = '2.0.0-rc6', default-features = false }
frame-support = { version = '2.0.0-rc6', default-features = false }
frame-system = { version = '2.0.0-rc6', default-features = false }
sp-api = { version = '2.0.0-rc6', default-features = false }
sp-block-builder = { version = '2.0.0-rc6', default-features = false }
sp-core = { version = '2.0.0-rc6', default-features = false }
sp-inherents = { version = '2.0.0-rc6', default-features = false }
sp-io = { version = '2.0.0-rc6', default-features = false }
sp-offchain = { version = '2.0.0-rc6', default-features = false }
sp-runtime = { version = '2.0.0-rc6', default-features = false }
sp-session = { version = '2.0.0-rc6', default-features = false }
sp-std = { version = '2.0.0-rc6', default-features = false }
sp-transaction-pool = { version = '2.0.0-rc6', default-features = false }
sp-version = { version = '2.0.0-rc6', default-features = false }


[build-dependencies]
wasm-builder-runner = { package = "substrate-wasm-builder-runner", version = "1.0.4" }

[features]
default = ["std"]
std = [
	# External dependencies
	"parity-scale-codec/std",
	"serde",

	# Substrate dependencies alphabetically
	"frame-executive/std",
	"frame-support/std",
	"frame-system/std",
	"sp-api/std",
	"sp-block-builder/std",
	"sp-core/std",
	"sp-inherents/std",
	"sp-io/std",
	"sp-offchain/std",
	"sp-runtime/std",
	"sp-session/std",
	"sp-std/std",
	"sp-transaction-pool/std",
	"sp-version/std",

	# Substrate Pallets
	"balances/std",
	"randomness-collective-flip/std",
	"sudo/std",
	"timestamp/std",
	"transaction-payment/std",

	# Recipes pallets
	"basic-token/std",
	"charity/std",
	"check-membership/std",
	"compounding-interest/std",
	"constant-config/std",
	"default-instance/std",
	"double-map/std",
	"fixed-point/std",
	"generic-event/std",
	"hello-substrate/std",
	"last-caller/std",
	"map-set/std",
	"randomness/std",
	"ringbuffer-queue/std",
	"simple-crowdfund/std",
	"simple-event/std",
	"simple-map/std",
	"storage-cache/std",
	"struct-storage/std",
	"vec-set/std",
]
