[package]
name = "super-runtime"
version = "3.0.0"
edition = "2018"
authors = ['Substrate DevHub <https://github.com/substrate-developer-hub>']
repository = 'https://github.com/substrate-developer-hub/recipes'
description = "A runtime that houses most of the Recipes' pallets"
license = "GPL-3.0-or-later"

[dependencies]
parity-scale-codec = { version = "2.0", default-features = false, features = ["derive"] }
serde = { version = "1.0", optional = true, features = ["derive"] }

# Substrate packages
pallet-balances = { version = '3.0', default-features = false }
frame-executive = { version = '3.0', default-features = false }
frame-support = { version = '3.0', default-features = false }
frame-system = { version = '3.0', default-features = false }
pallet-randomness-collective-flip = { version = '3.0', default-features = false }
sp-api = { version = '3.0', default-features = false }
sp-block-builder = { version = '3.0', default-features = false }
sp-core = { version = '3.0', default-features = false }
sp-inherents = { version = '3.0', default-features = false }
sp-io = { version = '3.0', default-features = false }
sp-offchain = { version = '3.0', default-features = false }
sp-runtime = { version = '3.0', default-features = false }
sp-session = { version = '3.0', default-features = false }
sp-std = { version = '3.0', default-features = false }
sp-transaction-pool = { version = '3.0', default-features = false }
sp-version = { version = '3.0', default-features = false }
pallet-sudo = { version = '3.0', default-features = false }
pallet-timestamp = { version = '3.0', default-features = false }
pallet-transaction-payment = { version = '3.0', default-features = false }

# local packages
basic-token = { path = "../../pallets/basic-token", default-features = false }
charity = { path = "../../pallets/charity", default-features = false }
check-membership = { path = "../../pallets/check-membership", default-features = false }
compounding-interest = { path = "../../pallets/compounding-interest", default-features = false }
constant-config = { path = "../../pallets/constant-config", default-features = false }
default-instance = { path = "../../pallets/default-instance", default-features = false }
double-map = { path = "../../pallets/double-map", default-features = false }
fixed-point = { path = "../../pallets/fixed-point", default-features = false }
generic-event = { path = "../../pallets/generic-event", default-features = false }
hello-substrate = { path = "../../pallets/hello-substrate", default-features = false }
last-caller = { path = "../../pallets/last-caller", default-features = false }
map-set = { path = "../../pallets/map-set", default-features = false }
randomness = { path = "../../pallets/randomness", default-features = false }
reservable-currency = { path = "../../pallets/reservable-currency", default-features = false }
ringbuffer-queue = { path = "../../pallets/ringbuffer-queue", default-features = false }
simple-crowdfund = { path = "../../pallets/simple-crowdfund", default-features = false}
simple-event = { path = "../../pallets/simple-event", default-features = false }
simple-map = { path = "../../pallets/simple-map", default-features = false }
storage-cache = { path = "../../pallets/storage-cache", default-features = false }
struct-storage = { path = "../../pallets/struct-storage", default-features = false }
vec-set = { path = "../../pallets/vec-set", default-features = false }

[build-dependencies]
substrate-wasm-builder = "4.0.0"

[features]
default = ["std"]
std = [
	"pallet-balances/std",
	"basic-token/std",
	"charity/std",
	"check-membership/std",
	"compounding-interest/std",
	"constant-config/std",
	"default-instance/std",
	"double-map/std",
	"fixed-point/std",
	"frame-executive/std",
	"frame-support/std",
	"frame-system/std",
	"generic-event/std",
	"hello-substrate/std",
	"last-caller/std",
	"map-set/std",
	"parity-scale-codec/std",
	"pallet-randomness-collective-flip/std",
	"randomness/std",
	"reservable-currency/std",
	"ringbuffer-queue/std",
	"serde",
	"simple-crowdfund/std",
	"simple-event/std",
	"simple-map/std",
	"sp-api/std",
	"sp-block-builder/std",
	"sp-core/std",
	"sp-inherents/std",
	"sp-io/std",
	"sp-offchain/std",
	"sp-runtime/std",
	"sp-session/std",
	"sp-std/std",
	"sp-transaction-pool/std",
	"sp-version/std",
	"storage-cache/std",
	"struct-storage/std",
	"pallet-sudo/std",
	"pallet-timestamp/std",
	"pallet-transaction-payment/std",
	"vec-set/std",
]
