[package]
name = "struct-storage"
version = "0.1.0"
authors = ["4meta5"]
edition = "2018"

[features]
default = ['std']
std = [
    'parity-scale-codec/std',
    'frame-support/std',
    'frame-system/std',
    'balances/std',
    'sp-runtime/std',
]

[dependencies.parity-scale-codec]
default-features = false
features = ['derive']
version = '1.1.0'

[dependencies.frame-support]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
rev = '1d8fa432949b99fac4ea0bebfdd6675dee973aa1'

[dependencies.frame-system]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
rev = '1d8fa432949b99fac4ea0bebfdd6675dee973aa1'

[dependencies.balances]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-balances'
rev = '1d8fa432949b99fac4ea0bebfdd6675dee973aa1'

[dependencies.sp-runtime]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
rev = '1d8fa432949b99fac4ea0bebfdd6675dee973aa1'

[dev-dependencies.primitives]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-core'
rev = '1d8fa432949b99fac4ea0bebfdd6675dee973aa1'

[dev-dependencies.sp-io]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
rev = '1d8fa432949b99fac4ea0bebfdd6675dee973aa1'
