[package]
name = "struct-storage"
version = "2.0.0-rc6"
authors = ['Substrate DevHub <https://github.com/substrate-developer-hub>']
repository = 'https://github.com/substrate-developer-hub/recipes'
edition = "2018"
license = "GPL-3.0-or-later"
description = "A pallet that demonstrates storing custom structs in Substrate storage"

[package.metadata.substrate]
categories = [
	"pallet",
	"tutorial",
	"recipe",
]
compatibility_version = "2.0.0-rc6"

[features]
default = ['std']
std = [
    'parity-scale-codec/std',
    'frame-support/std',
    'frame-system/std',
    'balances/std',
    'sp-runtime/std',
]

[dependencies]
parity-scale-codec = { version = "1.3.0", features = ["derive"], default-features = false }
frame-support = { version = '2.0.0-rc6', default-features = false }
frame-system = { version = '2.0.0-rc6', default-features = false }
sp-runtime = { version = '2.0.0-rc6', default-features = false }
balances = { package = 'pallet-balances', version = '2.0.0-rc6', default-features = false }

[dev-dependencies]
sp-core = { version = '2.0.0-rc6', default-features = false }
sp-io = { version = '2.0.0-rc6', default-features = false }
