[package]
name = 'super-genesis'
version = "2.0.0"
authors = ["Anonymous"]
edition = "2018"

[dependencies.runtime]
package = 'super-runtime'
path = '../super-runtime'

[dependencies]
babe-primitives = { package = "sp-consensus-babe", git = "https://github.com/paritytech/substrate", rev = 'ba5c85add52897acbd98f382ae11f7a11583e322' }
grandpa-primitives = { package = "sp-finality-grandpa", git = "https://github.com/paritytech/substrate", rev = 'ba5c85add52897acbd98f382ae11f7a11583e322' }
