[package]
name = 'weight-fee-genesis'
version = "2.0.0"
authors = ["Anonymous"]
edition = "2018"

[dependencies.runtime]
package = 'weight-fee-runtime'
path = '../weight-fee-runtime'

[dependencies]
babe-primitives = { package = "sp-consensus-babe", git = "https://github.com/paritytech/substrate", rev = '0bd9ffacdeb9bf3c97c04114de2cca5490ee98b6' }
grandpa-primitives = { package = "sp-finality-grandpa", git = "https://github.com/paritytech/substrate", rev = '0bd9ffacdeb9bf3c97c04114de2cca5490ee98b6' }
