[package]
name = "sum-storage-runtime-api"
version = "2.0.0"
authors = ['Substrate DevHub <https://github.com/substrate-developer-hub>']
edition = "2018"
license = "GPL-3.0-or-later"

[dependencies]
sp-api = { version = '2.0.0-rc4', default-features = false}

[dev-dependencies]
serde_json = "1.0.41"

[features]
default = ["std"]
std = [
	"sp-api/std",
]
