[package]
name = "simple-event"
version = "2.0.0-rc2"
authors = ["4meta5"]
repository = 'https://github.com/substrate-developer-hub/recipes'
edition = "2018"
license = "GPL-3.0-or-later"
description = "A pallet that emits simple events that do not encapsulate generic data types"

[package.metadata.substrate]
categories = [
	"pallet",
	"tutorial",
	"recipe",
]
compatibility_version = "2.0.0-rc2"

[features]
default = ['std']
std = [
    'parity-scale-codec/std',
    'frame-support/std',
    'system/std',
    'sp-runtime/std',
]

[dependencies]
parity-scale-codec = { version = "1.3.0", features = ["derive"], default-features = false }
frame-support = { package = "frame-support", version = '2.0.0-rc2', default-features = false }
system = { package = "frame-system", version = '2.0.0-rc2', default-features = false }
sp-runtime = { version = '2.0.0-rc2', default-features = false }

[dev-dependencies]
sp-core = { version = '2.0.0-rc2', default-features = false }
sp-io = { version = '2.0.0-rc2', default-features = false }
