[package]
authors = ['Joshy Orndorff']
edition = '2018'
homepage = 'https://substrate.dev/recipes'
name = 'basic-pow'
repository = 'https://github.com/substrate-developer-hub/recipes'
version = "2.0.0"

[[bin]]
name = 'basic-pow'
path = 'src/main.rs'

[dependencies]
futures = '0.3.1'
log = '0.4.8'
structopt = '0.3.8'
parity-scale-codec = '1.0.0'
sha3 = "0.8"
rand = { version = "0.7", features = ["small_rng"] }
sc-consensus-pow = { version = '0.8.0-alpha.5' }
sp-consensus-pow = { version = '0.8.0-alpha.5' }
sc-client-api = { version = '2.0.0-alpha.5' }
sp-blockchain = { version = '2.0.0-alpha.5' }
runtime = { package = "pow-runtime", path = "../../runtimes/pow-runtime" }
sp-timestamp = '2.0.0-alpha.5'
sc-basic-authorship = '0.8.0-alpha.5'
sc-cli = '0.8.0-alpha.5'
sc-client = '0.8.0-alpha.5'
sc-executor = '0.8.0-alpha.5'
sc-network = '0.8.0-alpha.5'
sc-service = '0.8.0-alpha.5'
sc-transaction-pool = '2.0.0-alpha.5'
sp-consensus = '0.8.0-alpha.5'
sp-core = '2.0.0-alpha.5'
sp-inherents = '2.0.0-alpha.5'
sp-runtime = '2.0.0-alpha.5'
sp-transaction-pool = '2.0.0-alpha.5'

[build-dependencies]
vergen = '3.0.4'
substrate-build-script-utils = '2.0.0-alpha.5'
