[package]
name = "account-set"
version = "2.0.0-rc4"
authors = ['Substrate DevHub <https://github.com/substrate-developer-hub>']
repository = 'https://github.com/substrate-developer-hub/recipes'
edition = "2018"
license = "GPL-3.0-or-later"
description = "A trait that supplies a set of accounts for use in a Substrate runtime"

[package.metadata.substrate]
categories = [
	"trait",
	"accounts",
	"recipe",
]
compatibility_version = "2.0.0-rc4"

[features]
default = ['std']
std = [
    'sp-std/std',
]

[dependencies]
sp-std = { version = '2.0.0-rc4', default-features = false }
