[package]
name = "vec-set"
version = "3.0.0"
edition = "2018"
repository = 'https://github.com/substrate-developer-hub/recipes'
authors = ['Substrate DevHub <https://github.com/substrate-developer-hub>']
description = "A pallet that implements a storage Set on top of a Vec"
license = "GPL-3.0-or-later"

[dependencies]
parity-scale-codec = { version = "2.0", features = ["derive"], default-features = false }

# Substrate packages

frame-support = { version = '3.0', default-features = false }
frame-system = { version = '3.0', default-features = false }
sp-runtime = { version = '3.0', default-features = false }
sp-std = { version = '3.0', default-features = false }

# local packages
account-set = { path = '../../traits/account-set', default-features = false }

[dev-dependencies]
sp-core = { version = '3.0', default-features = false }
sp-io = { version = '3.0', default-features = false }
serde = '1.0'

[features]
default = ['std']
std = [
	'account-set/std',
	'frame-support/std',
	'frame-system/std',
	'parity-scale-codec/std',
	'sp-runtime/std',
]
