[package]
name = "storage-cache"
version = "2.0.0-rc4"
authors = ['Substrate DevHub <https://github.com/substrate-developer-hub>']
repository = 'https://github.com/substrate-developer-hub/recipes'
edition = "2018"
license = "GPL-3.0-or-later"
description = "A pallet that demonstrates caching values read from storage to improve performance"

[package.metadata.substrate]
categories = [
	"pallet",
	"tutorial",
	"recipe",
]
compatibility_version = "2.0.0-rc4"

[dependencies]
# external dependencies
parity-scale-codec = { default-features = false, features = ['derive'], version = '1.3.0' }

# Substrate pallet/frame dependencies
frame-support = { package = 'frame-support', version = '2.0.0-rc4', default-features = false }
frame-system = { package = 'frame-system', version = '2.0.0-rc4', default-features = false }
sp-runtime = { version = '2.0.0-rc4', default-features = false }
sp-std = { version = '2.0.0-rc4', default-features = false }

[dev-dependencies]
sp-core = { version = '2.0.0-rc4', default-features = false }
sp-io = { version = '2.0.0-rc4', default-features = false }

[features]
default = ['std']
std = [
	'parity-scale-codec/std',
	'frame-support/std',
	'frame-system/std',
	'sp-runtime/std',
]
