name: Build and Push Playground Image

on:
  push:
    branches:
    - master

jobs:
  build-push-template:
    if: ${{ github.repository == 'substrate-developer-hub/recipes' }}
    runs-on: ubuntu-18.04
    steps:
    - name: Trigger playground inclusion
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: paritytech/substrate-playground
        event-type: template-updated
        client-payload: '{"id": "recipes"}'
